services:
  kephalosdata:
    image: ghcr.io/666ghj/kephalosdata:latest
    # Accelerated mirror (if pulling is slow, use the above address)
    # image: ghcr.nju.edu.cn/666ghj/kephalosdata:latest
    container_name: kephalosdata
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads